### ISSUE TITLE
Index page appers to be broken

### ISSUE THREAD

**Issue by Rubaabali** [IsVipiOfficial/IsVipi-OSSN#11]
I installed isvipi on my lamp and my operating system is ubuntu 14.04. mysql 5.6

Screen is complete blue without any button but only has isvipi logo and two select fields..
![ubuntu](https://cloud.githubusercontent.com/assets/18479206/14554707/0c985568-0308-11e6-9880-66d6bded0266.png)

**Comment by IsVipiOfficial** [comment]
To begin with, did you download your IsVipi set up from Github or our website. Also, can you gain access to the admin backend (http://yoursite.com/admin)? If you can, under general settings, uncheck "Hide PHP errors" then visit the homepage and see what error comes up.

**Comment by Rubaabali** [comment]
Thanks for reply ... sorry for being to late to reply for above mentioned issue.. i open mysite/admin but still not getting submit button only two text fields are displayed can you tell me from which file i should turn errors on ? @IsVipiOfficial

**Comment by IsVipiOfficial** [comment]
In this case then you have to change an entry in the database. In the database, find table "s_settings", column named "errors" and chnage the value from 1 to 0.

**Comment by alexlupoz** [comment]
Hi, @IsVipiOfficial 

I have the same problem :/ But changing de value to "0" in table "s_settings", don't fix the problem. Can you help me?

![image](https://user-images.githubusercontent.com/34819756/36693119-050ae61e-1b19-11e8-8432-bd3e3c4d535e.png)
