### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by stewie27** [IsVipiOfficial/IsVipi-OSSN#3]
![image](https://cloud.githubusercontent.com/assets/14852765/10175117/2a1c037e-66e5-11e5-94b2-7dfd7b699057.png)

**Comment by IsVipiOfficial** [comment]
That is because you have not yet set up the database. This is a completely new framework for IsVipi OSSN. The current one has been depreciated. Please give me a few more weeks and you will have everything running perfectly again. If you would like to contribute in the developement, you can let me know.

**Comment by stewie27** [comment]
i had set up the database edited the db details to point to my db and also imported the sql thats when i get the error ? also yeah can help out if you would like?

**Comment by IsVipiOfficial** [comment]
Okay. Using phpMyAdmin or any software of your choice, find table "s_info" in your database and enter values as shown in the screenshot below. Make sure to change the details to match where you have installed your test server for the script (mine is at http://localhost/isvipi). Fill the rest of the details as they appear in the screenshot.
![localhost 127 0 0 1 isvipi s_info phpmyadmin 4 4 14](https://cloud.githubusercontent.com/assets/5174371/10347429/7cec5b1e-6d3c-11e5-85e3-264233c91828.png)

**Comment by stewie27** [comment]
fixed, cheers. i never thought of that. anyways its looking pretty impressive, when there is a little more functionality i will start contributing themes :)

**Comment by IsVipiOfficial** [comment]
No problem. Check the repo as often as you can since I will be updating it everyday.

**Comment by stewie27** [comment]
latest version (fresh install) is now showing no feeds in database under feeds table it shows all feeds are there

**Comment by IsVipiOfficial** [comment]
Is there any error that you can see? There are several possibilities for that but mostly it could be an issue with your site url. Check your site url in the database (table s_info) and make sure it is correct and does not have any trailing front slash "/" at the end. 

If the feeds still do not load, if you are on chrome, launch the the developer console (f12) and under tab console, reload the page and take note of any error. Oh! Also check if javascript is enabled on your browser as it could also be a javascript issue.

**Comment by stewie27** [comment]
console errors are as follows

GET https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css net::ERR_NETWORK_CHANGED
localhost/:18 GET https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic net::ERR_NETWORK_CHANGED

no trailing slash '/' and url and java are both enabled
plus previous versions worked

**Comment by IsVipiOfficial** [comment]
Is you internet enabled? It appears that your installation cannot load required resources. Are you testing it on a local server?

**Comment by stewie27** [comment]
yeah, my internet is on as im on here and other site aswell an yeah using wamp

**Comment by IsVipiOfficial** [comment]
You can have alook at this http://superuser.com/questions/747735/regularly-getting-err-network-changed-errors-in-chrome or http://www.pcappspot.com/fix-err-network-changed-windows/. And have you tried a different browser apart from chrome?

**Comment by IsVipiOfficial** [comment]
Also, when you did a fresh install, did you delete all tables in the database and imported them a fresh? I made some changes to the database structure so I hope you made a fresh install of the database as well.

**Comment by stewie27** [comment]
all fixed :) i was missing a file :) cheers

**Comment by IsVipiOfficial** [comment]
Great..

**Comment by stewie27** [comment]
hi, i have managed to fix some of the theme issues :) aswell as add a new page to the profile and also edited the chatbar and menu sidebar too ill upload it here soon so you can take a look :)

**Comment by IsVipiOfficial** [comment]
Let me have a look

**Comment by IsVipiOfficial** [comment]
This is way better. I wish you had told me you were working on it so that I could have found a way of getting your changes. I would like some specific changes that you have made to the template already (if you don't mind). Have you forked the project?

**Comment by stewie27** [comment]
No as I forgot how to do it

**Comment by stewie27** [comment]
Also I have noticed one issue in the messages that the sidebar doesn't keep chats as it shows new but once replied it vanishes (maybe due to a change I made) not sure yet? Something to look into I guess

**Comment by IsVipiOfficial** [comment]
I have made quite a number of changes so far and it would be relatively tedious going through the code again trying to find the exact changes you made. I was mainly interested with the way you designed the profile page, plus the additional page and the left sidebar with "view profile". Anyway, when I get time I will try and see what I can extract.

**Comment by stewie27** [comment]
isv_themes\default\profile.php for the profile design
isv_themes\default\ovr\sidebar.php for the view profile design :)

**Comment by stewie27** [comment]
any eta as to when the backend is started/finished?

**Comment by IsVipiOfficial** [comment]
I have just finished working on the automatic (step by step) installation and even released it for testing. I may start working on the admin backend tomorrow but I am not sure since I feel the main website http://isvipi.org needs a facelift. I am still torn between a facelift while I fix bug reports (if any) or proceeding with the admin backend.

**Comment by stewie27** [comment]
new 2nd theme option for you http://www.bootstrapzero.com/bootstrap-template/google-plus

**Comment by IsVipiOfficial** [comment]
I'd seen it but it didn't really have what I was looking for.
