### ISSUE TITLE
anable to load css and javascript

### ISSUE THREAD

**Issue by GaneshKandu** [IsVipiOfficial/IsVipi-OSSN#4]
Hi ,Its Ganesh Kandu
I have installed IsVipi-OSSN 1.3.0 on My Wamp but getting an error during page load css and javascripts are not getting load and working very well on lamp, please help
I think i may know the region
its due to wrong path of javascript and css 
i should may like <q>/inc/style.lib<b>/</b>css/bootstrap.min.css</q>
but it seems like <q>/inc/style.lib<b>%5C</b>css/bootstrap.min.css</q>

**Comment by IsVipiOfficial** [comment]
Hi Ganesh. Unfortunately we no longer offer support for version 1.xx of IsVipi. Could you please kindly try the latest release though it is only out for testing? Version 1.xx has been depreciated

**Comment by GaneshKandu** [comment]
Hi, Can you Give me a link to Download a supported version of IsVipi so that i can Downloads

**Comment by GaneshKandu** [comment]
Hi , is 2.0.0 your supported version

**Comment by IsVipiOfficial** [comment]
Noted Ganesh. With the latest updates, the size of the site url has been increased to 255. As for the "DIRECTORY_SEPARATOR" issue, it should still work on a windows platform.

**Comment by GaneshKandu** [comment]
Thanks to reply
i am using firefox v.45.0.1 and its not working in it but yes its working on chrome v.49.0.2623.108

**Comment by IsVipiOfficial** [comment]
Thank you for pointing that out. The issues has been noted.
